name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deployment

env:
  PROJECT_ID: businesscard-474411
  REGION: asia-south1   # change if different
  SERVICE_NAME: fullstack
  REPO_NAME: ai-card-scanner
  IMAGE: asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3️⃣ Build and push the Docker image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag $IMAGE ./backend

      # 4️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
