name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: businesscard-474411
  REGION: asia-south1
  SERVICE_NAME: fullstack
  REPO_NAME: ai-card-scanner

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3️⃣ Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${SERVICE_NAME}"
          gcloud builds submit --tag $IMAGE ./backend

      # 4️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${SERVICE_NAME}"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
